<?php

namespace Emds\MiniBlogBundle\Entity;
require("C:\wamp\www\miniBlog\src\Emds\MiniBlogBundle\Entity\Message.php");

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-22 at 13:55:41.
 */
class MessageTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Message
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Message;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (1, 2) == 3.
     *
     * @covers Emds\MiniBlogBundle\Entity\Message::addition
     */
    public function testAddition() {
        $this->assertEquals(
                3, $this->object->addition(1, 2)
        );
    }

    /**
     * Generated from @assert (2) == 5.
     *
     * @covers Emds\MiniBlogBundle\Entity\Message::double
     */
    public function testDouble() {
        $this->assertEquals(
                5, $this->object->double(2)
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::setDate
     * @todo   Implement testSetDate().
     */
    public function testSetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::getDate
     * @todo   Implement testGetDate().
     */
    public function testGetDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::setTitre
     * @todo   Implement testSetTitre().
     */
    public function testSetTitre() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::getTitre
     * @todo   Implement testGetTitre().
     */
    public function testGetTitre() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::setAuteur
     * @todo   Implement testSetAuteur().
     */
    public function testSetAuteur() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::getAuteur
     * @todo   Implement testGetAuteur().
     */
    public function testGetAuteur() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::setContenu
     * @todo   Implement testSetContenu().
     */
    public function testSetContenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Emds\MiniBlogBundle\Entity\Message::getContenu
     * @todo   Implement testGetContenu().
     */
    public function testGetContenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
